### ISSUE TITLE
Future roadmap.

### ISSUE THREAD

**Issue by chengluyu** [chengluyu/PL0#2]
Features:
- [ ] Add detection of stack overflow.
- [ ] Rewrite option parser.
- [ ] Add more debug flags (`--show-track`, `--breakpoint`, `--show-locals`, etc)

To myself: those work should be started at 30th Oct and do not spend time on this project before that day.
